spring.application.name=microfit

spring.datasource.url=jdbc:mysql://localhost:3306/microfit
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true